#!/usr/bin/env ruby

# Para corrigir os problemas de codificação no Windows #98
Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8


require 'json'

data = JSON.parse(STDIN.read)

$stdout << data.to_json

