#!/usr/bin/env ruby

# Para corrigir os problemas de codificação no Windows #98
Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

require 'pandoc_abnt'

quadros_filtrados = PandocAbnt::QuadroFilter.new.filtra_json(STDIN.read)

figura_filtradas = PandocAbnt::FiguraFilter.new.filtra_json(quadros_filtrados)

$stdout << PandocAbnt::ListaFilter.new.filtra_json(figura_filtradas)

